spring.application.name=course
spring.profiles.active=test
#open-in-view=true permite ao Jackson (lib que serializa o json do Spring JPA carregar dados das associações)
spring.jpa.open-in-view=true

logging.level.org.springframework.web=ERROR
logging.level.org.springframework.dao=ERROR
logging.level.org.springframework.data.jpa=ERROR
logging.level.com.mkyong=DEBUG
